name: Push result
on: workflow_dispatch
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create report file
        run: |
          date +%s > report.txt   # Create an example file
      - name: Commit report
        run: |
          git add --all
          git fetch
          git checkout -b build --track origin/build  # Checkout build branch (must exist already)
          mkdir -p build
          rm -rf ./build/*
          git diff --cached --name-only | xargs -I% mv "%" build/  # Move all new files to build directory
          shopt -s extglob
          rm -rf !(build)  # Remove everything else to keep the branch tidy
          git add --all
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git config --global user.name "${{github.actor}}"
          git commit -am "Automated report"
          git push  
